# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# -------------------------------------------------------------------



################
### MONITORS ###
################
source = ~/.config/hypr/conf/monitors.conf


###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/conf/programs.conf


#################
### AUTOSTART ###
#################
source = ~/.config/hypr/conf/autostart.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/conf/environment.conf


#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/animation.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf


#############
### INPUT ###
#############
source = ~/.config/hypr/conf/input.conf


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/conf/keybinding.conf


####################
### WINDOWS RULE ###
####################
source = ~/.config/hypr/conf/windowrule.conf


#######################
### WORKSPACES RULE ###
#######################
source = ~/.config/hypr/conf/workspaces.conf


#######################
### ENVIROMENT VARIABLES ###
#######################

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = __GL_GSYNC_ALLOWED,1

# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

input {
    follow_mouse = 0
}

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.

# Override keybindings to use cyclic focus (safer para alternar entre 2 apps no mesmo monitor)
# Essas linhas forçam o comportamento depois do Ambxst (que é carregado acima)
bind = SUPER, Left, cyclenext, prev
bind = SUPER, Right, cyclenext
bind = SUPER, Up, cyclenext, prev
bind = SUPER, Down, cyclenext
