# ~/.config/hypr/hyprpaper.conf

splash = false
ipc = on

# ── Preload: wallpapers de ~/Pictures/Wallpapers/ ──
preload = /home/william/Pictures/Wallpapers/wallhaven_7331ko.jpg
preload = /home/william/Pictures/Wallpapers/wallhaven_95ej2k.jpg

# ── Todos os monitores usam o mesmo wallpaper ──
wallpaper = ,/home/william/Pictures/Wallpapers/wallhaven_7331ko.jpg